package docker

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// ComposeManager manages docker-compose files for contexts.
type ComposeManager struct {
	ProjectPath string
}

// NewComposeManager creates a new compose manager.
func NewComposeManager(projectPath string) *ComposeManager {
	return &ComposeManager{
		ProjectPath: projectPath,
	}
}

// GenerateOverride generates a docker-compose override file for a context.
func (cm *ComposeManager) GenerateOverride(ctxName string, ports map[string]int) error {
	overridePath := filepath.Join(cm.ProjectPath, "..", ctxName, "docker-compose.dcell.yml")

	content := cm.generateOverrideContent(ports)

	if err := os.WriteFile(overridePath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write override file: %w", err)
	}

	return nil
}

// GenerateEnv generates environment file for a context.
func (cm *ComposeManager) GenerateEnv(ctxName string, ports map[string]int) error {
	envPath := filepath.Join(cm.ProjectPath, "..", ctxName, ".env.dcell")

	var lines []string
	lines = append(lines, fmt.Sprintf("# Auto-generated by dcell for context: %s", ctxName))
	lines = append(lines, "")

	for service, port := range ports {
		lines = append(lines, fmt.Sprintf("%s_PORT=%d", strings.ToUpper(service), port))
	}

	// Add common database URLs
	if dbPort, ok := ports["db"]; ok {
		lines = append(lines, fmt.Sprintf("DATABASE_URL=postgres://localhost:%d/app_%s", dbPort, ctxName))
		lines = append(lines, fmt.Sprintf("POSTGRES_PORT=%d", dbPort))
	}
	if redisPort, ok := ports["redis"]; ok {
		lines = append(lines, fmt.Sprintf("REDIS_URL=redis://localhost:%d", redisPort))
		lines = append(lines, fmt.Sprintf("REDIS_PORT=%d", redisPort))
	}

	content := strings.Join(lines, "\n") + "\n"

	if err := os.WriteFile(envPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write env file: %w", err)
	}

	return nil
}

// Cleanup removes generated files for a context.
func (cm *ComposeManager) Cleanup(ctxName string) error {
	ctxPath := filepath.Join(cm.ProjectPath, "..", ctxName)
	
	files := []string{
		filepath.Join(ctxPath, "docker-compose.dcell.yml"),
		filepath.Join(ctxPath, ".env.dcell"),
	}

	for _, f := range files {
		os.Remove(f)
	}

	return nil
}

func (cm *ComposeManager) generateOverrideContent(ports map[string]int) string {
	var lines []string
	lines = append(lines, "# Auto-generated by dcell")
	lines = append(lines, "version: '3.8'")
	lines = append(lines, "services:")

	// Generate port mappings for known services
	for service, port := range ports {
		switch service {
		case "app", "web", "api":
			lines = append(lines, fmt.Sprintf("  %s:", service))
			lines = append(lines, "    ports:")
			lines = append(lines, fmt.Sprintf("      - \"%d:%d\"", port, port))
		case "db":
			lines = append(lines, "  db:")
			lines = append(lines, "    ports:")
			lines = append(lines, fmt.Sprintf("      - \"%d:5432\"", port))
			lines = append(lines, "    environment:")
			lines = append(lines, fmt.Sprintf("      POSTGRES_DB: app_%d", port-5432))
		case "redis":
			lines = append(lines, "  redis:")
			lines = append(lines, "    ports:")
			lines = append(lines, fmt.Sprintf("      - \"%d:6379\"", port))
		case "mongo":
			lines = append(lines, "  mongo:")
			lines = append(lines, "    ports:")
			lines = append(lines, fmt.Sprintf("      - \"%d:27017\"", port))
		}
	}

	return strings.Join(lines, "\n") + "\n"
}

// Start starts docker-compose for a context.
func Start(ctxPath string) error {
	// Try docker compose (new) first, fall back to docker-compose (old)
	cmd := exec.Command("docker", "compose", "-f", "docker-compose.yml", "-f", "docker-compose.dcell.yml", "up", "-d")
	cmd.Dir = ctxPath
	if err := cmd.Run(); err != nil {
		cmd = exec.Command("docker-compose", "-f", "docker-compose.yml", "-f", "docker-compose.dcell.yml", "up", "-d")
		cmd.Dir = ctxPath
		return cmd.Run()
	}
	return nil
}

// Stop stops docker-compose for a context.
func Stop(ctxPath string) error {
	cmd := exec.Command("docker", "compose", "-f", "docker-compose.yml", "-f", "docker-compose.dcell.yml", "stop")
	cmd.Dir = ctxPath
	if err := cmd.Run(); err != nil {
		cmd = exec.Command("docker-compose", "-f", "docker-compose.yml", "-f", "docker-compose.dcell.yml", "stop")
		cmd.Dir = ctxPath
		return cmd.Run()
	}
	return nil
}
